spring:
  application:
    name: "polyglots"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        default_schema: "public"

appdb:
  datasource:
    jdbc-url: ""
    username: ""
    password: ""
    pool-name: "Hikari-yb-pool"
    maximum-pool-size: 4
    validation-query: "Select 1"
    testOnBorrow: true


azure:
  cognitiveservice:
    subscriptionkey: "3bb7968a4024404187a5a95c4c82548f"
    serviceregion: "eastus"

