spring:
  application:
    name: "polyglots"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        default_schema: "public"

appdb:
  datasource:
    jdbc-url: ""
    username: ""
    password: ""
    pool-name: "Hikari-yb-pool"
    maxLifetime: 60000
    maximum-pool-size: 15
    validation-query: "Select 1"
    test-on-borrow: true
    test-while-idle: true
    max-life-time: 120000

azure:
  cognitiveservice:
    subscriptionkey: ""
    serviceregion: ""

