spring:
  application:
    name: "polyglots"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        default_schema: "public"

appdb:
  datasource:
    jdbc-url: "jdbc:postgresql://20.127.243.191:5433/yugabyte"
    username: "yugabyte"
    password: "Hackathon22!"
    pool-name: "Hikari-yb-pool"
    maxLifetime: 60000
    maximum-pool-size: 15
    validation-query: "Select 1"
    test-on-borrow: true
    test-while-idle: true
    max-life-time: 120000

azure:
  cognitiveservice:
    subscriptionkey: "3bb7968a4024404187a5a95c4c82548f"
    serviceregion: "eastus"

